-- Retrieve all restaurant names and addresses
SELECT Name, Address FROM Restaurants;

-- List users and their types
SELECT Username, UserType FROM Users;

-- Find top-rated restaurants
SELECT Name, Rating FROM Restaurants WHERE Rating > 4.5;

-- Get order details including item names for a order
-- RA EXPRESSION
SELECT O.OrderID, M.Name, M.Price, D.Quantity
FROM Orders O
JOIN OrderDetails D ON O.OrderID = D.OrderID
JOIN MenuItems M ON D.MenuItemID = M.MenuItemID
WHERE O.OrderID = 1;

-- Find the total revenue generated by each restaurant
-- RA EXPRESSION
SELECT R.Name, SUM(P.Amount) AS TotalRevenue
FROM Restaurants R
JOIN Orders O ON R.RestaurantID = O.RestaurantID
JOIN Payments P ON O.OrderID = P.OrderID
GROUP BY R.Name;

-- List all drivers who have delivered more than 2 orders
SELECT U.Username, COUNT(O.OrderID) AS Deliveries
FROM Users U
JOIN Orders O ON U.UserID = O.DriverID
WHERE U.UserType = 'Driver'
GROUP BY U.Username
HAVING Deliveries > 2;

-- Show the average rating for each restaurant
-- RA EXPRESSION
SELECT R.Name, AVG(Ra.Score) AS AverageRating
FROM Restaurants R
JOIN Ratings Ra ON R.RestaurantID = Ra.RestaurantID
GROUP BY R.Name;

-- List all orders that are pending payment
SELECT O.OrderID, O.TotalPrice
FROM Orders O
JOIN Payments P ON O.OrderID = P.OrderID
WHERE P.PaymentStatus = 'Pending';

-- Display restaurants and their active menu items count
SELECT R.Name, COUNT(M.MenuItemID) AS MenuItemsCount
FROM Restaurants R
JOIN MenuItems M ON R.RestaurantID = M.RestaurantID
GROUP BY R.Name;

--  Find all customers who have placed orders for 'Pizza'
SELECT DISTINCT U.Username
FROM Users U
JOIN Orders O ON U.UserID = O.UserID
JOIN OrderDetails D ON O.OrderID = D.OrderID
JOIN MenuItems M ON D.MenuItemID = M.MenuItemID
WHERE M.Name LIKE '%Pizza%';


SELECT UserID, Username, UserType, Email FROM Users;



SELECT u.UserID, u.Username, u.Email, d.LicenseNumber, d.VehicleType
FROM Users u
JOIN Drivers d ON u.UserID = d.DriverID;



SELECT RestaurantID, Name, Address, IsActive FROM Restaurants;



SELECT m.MenuItemID, m.Name, m.Description, m.Price, r.Name AS RestaurantName 
FROM MenuItems m 
JOIN Restaurants r ON m.RestaurantID = r.RestaurantID;



SELECT OrderStatus, COUNT(*) AS Count FROM Orders GROUP BY OrderStatus;


-- 
SELECT RestaurantID, AVG(TIMESTAMPDIFF(MINUTE, OrderTime, NOW())) AS AvgTime
FROM Orders
WHERE OrderStatus = 'Delivered'
GROUP BY RestaurantID;

